### ISSUE TITLE
micro-app vuedraggable  vue2 component undefined

### ISSUE THREAD

**Issue by panjunliang** [jd-opensource/micro-app#1022]
## 问题描述
> 问题的具体描述

## 复现步骤
1.vue2环境
2.vuedraggable  插件引入业务系统

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
main.js:79 TypeError: Cannot read properties of undefined (reading 'component')
    at Module.fb15 (vuedraggable.umd.js:2440:14)
    at __webpack_require__ (vuedraggable.umd.js:25:30)
    at eval (vuedraggable.umd.js:89:18)
    at eval (vuedraggable.umd.js:92:10)
    at webpackUniversalModuleDefinition (vuedraggable.umd.js:3:20)
    at Object.eval (vuedraggable.umd.js:5:3)
    at ./node_modules/vuedraggable/dist/vuedraggable.umd.js (chunk-libs.js:4927:1)
    at __webpack_require__ (runtime.js:80:30)
    at Object.eval (add.vue?./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??vue-loader-options:9:44)
    at ./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/views/set/contractTemplateForm/add.vue?vue&type=script&lang=js& (app.js:551:1)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：^1.0.0-alpha.7
- 主应用前端框架&版本：2.6.12
- 子应用前端框架&版本：2.6.12
- 构建工具&版本：npm

https://github.com/micro-zoe/micro-app/issues/686 
这个问题为什么关闭了，我现在遇到了这个问题，一个菜鸟前端的提问，大佬能解决吗，有方法吗,jd大佬

**Comment by bailicangdu** [comment]
升级到最新版即可解决
