### ISSUE TITLE
本地npm run build编译源码报错

### ISSUE THREAD

**Issue by bayuango** [jd-opensource/micro-app#1100]
## 问题描述
> 问题的具体描述
运行npm run build，报以下错误：
> @micro-zoe/micro-app@1.0.0-rc.4 createtype D:\projects\tests\MicroApps\micro-app
> node scripts/create_type.js

生成*.d.ts文件失败
D:\projects\tests\MicroApps\micro-app\scripts\create_type.js:64
    throw e
    ^

AssertionError [ERR_ASSERTION]: main does not exist: D:\projects\tests\MicroApps\micro-app\lib\lib\index.d.ts
    at Object.bundle (D:\projects\tests\MicroApps\micro-app\node_modules\dts-bundle\lib\index.js:79:9)
    at createDts (D:\projects\tests\MicroApps\micro-app\scripts\create_type.js:47:9)
    at Object.<anonymous> (D:\projects\tests\MicroApps\micro-app\scripts\create_type.js:68:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @micro-zoe/micro-app@1.0.0-rc.4 createtype: `node scripts/create_type.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @micro-zoe/micro-app@1.0.0-rc.4 createtype script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Program Files\nodejs\node_cache\_logs\2024-02-22T01_22_42_299Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @micro-zoe/micro-app@1.0.0-rc.4 build: `cross-env NODE_ENV='production' rollup -c && npm run createtype && npm run afterbuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @micro-zoe/micro-app@1.0.0-rc.4 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

## 复现步骤
1.拉取源码，安装依赖
2.运行npm run build，报错

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：
- 子应用前端框架&版本：
- 构建工具&版本：

**Comment by bayuango** [comment]
![企业微信截图_17086807671526](https://github.com/micro-zoe/micro-app/assets/13271028/7c0f39aa-33a3-4c1f-9081-caf8983897c5)
