### ISSUE TITLE
can't run at windows

### ISSUE THREAD

**Issue by byoungd** [jd-opensource/micro-app#40]
设备名称	han-PC
处理器	Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz   4.20 GHz
机带 RAM	32.0 GB
设备 ID	F5C3BF9B-6342-43FE-98BD-04C8A34B7F12
产品 ID	00331-10000-00001-AA107
系统类型	64 位操作系统, 基于 x64 的处理器

`yarn build:watch` 

@micro-zoe/micro-app@0.2.2 build D:\DEV\github\micro-app
> cross-env NODE_ENV='production' rollup -c && npm run createtype && npm run afterbuild

[!] SyntaxError: Unexpected token '.'
D:\DEV\github\micro-app\rollup.config.js:102
polyfillFiles?.forEach((file) => {
              ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.require.extensions.<computed> [as .js] (D:\DEV\github\micro-app\node_modules\rollup\dist\shared\loadConfigFile.js:513:20)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at loadConfigFromBundledFile (D:\DEV\github\micro-app\node_modules\rollup\dist\shared\loadConfigFile.js:521:42)
    at getDefaultFromTranspiledConfigFile (D:\DEV\github\micro-app\node_modules\rollup\dist\shared\loadConfigFile.js:505:12)
    at loadConfigFile (D:\DEV\github\micro-app\node_modules\rollup\dist\shared\loadConfigFile.js:483:15)

----

change  rollup.config.js line 89

remove the `?` and it's working.

Is this a issue that using optional chaining in rollup.config.js  file without any config?

**Comment by loo41** [comment]
升级 node.js 版本，?. 语法不支持。 node >= 14.5(https://node.green/)

**Comment by byoungd** [comment]
> 升级 node.js 版本，?. 语法不支持。 node >= 14.5(https://node.green/)

 ok
