### ISSUE TITLE
主应用中两个微应用之间使用webpack5模块联邦报错

### ISSUE THREAD

**Issue by cnLiuMing** [jd-opensource/micro-app#410]
## 问题描述
> 问题的具体描述
两个微应用单独启动访问可以使用模块联邦
通过主应用访问其中一个微应用报错

## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
VM6405:31 
        
Uncaught (in promise) ScriptExternalLoadError: Loading script failed.
(missing: http://localhost:10001/remoteEntry.js)
while loading "./HelloWorld.vue" from webpack/container/reference/app_exposes
    at Object.webpack/container/reference/app_exposes (eval at runCode2Function (scripts.ts:353:26), <anonymous>:31:25)
    at __webpack_require__ (eval at runCode2Function (scripts.ts:353:26), <anonymous>:73:33)
    at initExternal (eval at runCode2Function (scripts.ts:353:26), <anonymous>:383:28)
    at Function.__webpack_require__.I (eval at runCode2Function (scripts.ts:353:26), <anonymous>:395:15)
    at eval (eval at runCode2Function (scripts.ts:353:26), <anonymous>:884:47)
    at Object.webpack/sharing/consume/default/vue/vue?2b38 (eval at runCode2Function (scripts.ts:353:26), <anonymous>:938:81)
    at eval (eval at runCode2Function (scripts.ts:353:26), <anonymous>:969:56)
    at Array.forEach (<anonymous>)
    at Object.__webpack_require__.f.consumes (eval at runCode2Function (scripts.ts:353:26), <anonymous>:952:36)
    at eval (eval at runCode2Function (scripts.ts:353:26), <anonymous>:188:40)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：
- 主应用前端框架&版本： vue3 + vite2
- 子应用前端框架&版本： vue3 + vue-cli4
- 构建工具&版本：

**Comment by bailicangdu** [comment]
这个问题已经在看了

**Comment by cnLiuMing** [comment]
> 



> 这个问题已经在看了

好的，辛苦

**Comment by neostfox** [comment]
今天我也遇到这个问题了。就很尴尬

**Comment by zhouyiwan** [comment]
这个问题应该是子应用的publicpath丢失了，可以固定一下子应用打包配置中的publicpath。
再加上联邦模块中的library配置
new ModuleFederationPlugin({
    name: 'react18_mf2',
    filename: 'remoteEntry.js',
    library: {
      name: 'react18_mf2',
      type: 'window',
    },
   ...
}

**Comment by hengyuli** [comment]
请问这个问题解决了吗？
俩个子应用可单独运行，在基座上运行A微应用 之后再运行B微应用 就报这个错
Container initialization failed as it has already been initialized with a different share scope

**Comment by Kevin9703** [comment]
我单独一个子应(umi4)用用webpack5 也会报错 Error: Container initialization failed as it has already been initialized with a different share scope

**Comment by UNDERCOVERj** [comment]
我这边也遇到了，Container initialization failed as it has already been initialized with a different share scope。请问问题有解决吗？

**Comment by Ink-o** [comment]
再蹲一个，有解决了吗？

**Comment by baosuyaole1** [comment]
同问楼上+1

**Comment by AburronKing** [comment]
@baosuyaole1 请问你解决了吗  @UNDERCOVERj

**Comment by baosuyaole1** [comment]
并没有看了一圈貌似有很多坑&nbsp; 打算弄一个微件化的包&nbsp; 发布npm&nbsp; 下载使用


高级Boss`
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "micro-zoe/micro-app"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月11日(星期二) 下午2:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [micro-zoe/micro-app] 主应用中两个微应用之间使用webpack5模块联邦报错 (Issue #410)





 
@baosuyaole1 请问你解决了吗  @UNDERCOVERj

**Comment by tpc-ht** [comment]
同问
