### ISSUE TITLE
umi4框架下生命周期函数不会执行

### ISSUE THREAD

**Issue by piczi** [jd-opensource/micro-app#473]
## 问题描述
> 问题的具体描述

## 复现步骤
1.安装umi4
2.在micro-app上调用onMounted

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：0.8.5
- 主应用前端框架&版本：umi4.0.5
- 子应用前端框架&版本："umi": "^3.5.20",
- 构建工具&版本："umi": "^3.5.20",
<img width="731" alt="企业微信20220708-185203@2x" src="https://user-images.githubusercontent.com/25976987/177978748-b0dbb8cd-2fda-4489-b696-de9915a84e0e.png">

**Comment by bailicangdu** [comment]
这个设置了吗
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/20297227/177983637-7e030f7f-7550-45f7-ba60-899cc5b31ebf.png">

**Comment by bailicangdu** [comment]
https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/life-cycles

**Comment by piczi** [comment]
> https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/life-cycles



> 这个设置了吗 <img alt="image" width="1027" src="https://user-images.githubusercontent.com/20297227/177983637-7e030f7f-7550-45f7-ba60-899cc5b31ebf.png">

但是加上这段代码umi4会运行出错：
`error - ./src/pages/dataSupport/index.tsx
Module build failed (from ./node_modules/@umijs/bundler-webpack/compiled/babel-loader/index.js):
SyntaxError: /Users/zhanglei/Documents/workspace/meichuang/mc-main-app/src/pages/dataSupport/index.tsx: importSource cannot be set when runtime is classic.
> 1 |
    | ^
  2 | /** @jsxRuntime classic */
  3 | /** @jsx jsxCustomEvent */
  4 | import jsxCustomEvent from '@micro-zoe/micro-app/polyfill/jsx-custom-event'
    at File.buildCodeFrameError (/Users/zhanglei/Documents/workspace/meichuang/mc-main-app/node_modules/@umijs/bundler-utils/compiled/babel/index.js:6312:12)
    at NodePath.buildCodeFrameError (/Users/zhanglei/Documents/workspace/meichuang/mc-main-app/node_modules/@umijs/bundler-utils/compiled/babel/index.js:91218:21)
    at PluginPass.enter (/Users/zhanglei/Documents/workspace/meichuang/mc-main-app/node_modules/@umijs/bundler-utils/compiled/babel/index.js:77415:28)
    at newFn (/Users/zhanglei/Documents/workspace/meichuang/mc-main-app/node_modules/@umijs/bundler-utils/compiled/babel/index.js:95018:21)
    at NodePath._call (/Users/zhanglei/Documents/workspace/meichuang/mc-main-app/node_modules/@umijs/bundler-utils/compiled/babel/index.js:89498:20)
    at NodePath.call (/Users/zhanglei/Documents/workspace/meichuang/mc-main-app/node_modules/@umijs/bundler-utils/compiled/babel/index.js:89485:17)
    at NodePath.visit (/Users/zhanglei/Documents/workspace/meichuang/mc-main-app/node_modules/@umijs/bundler-utils/compiled/babel/index.js:89545:31)
    at TraversalContext.visitQueue (/Users/zhanglei/Documents/workspace/meichuang/mc-main-app/node_modules/@umijs/bundler-utils/compiled/babel/index.js:89020:16)
    at TraversalContext.visitSingle (/Users/zhanglei/Documents/workspace/meichuang/mc-main-app/node_modules/@umijs/bundler-utils/compiled/babel/index.js:88994:19)
    at TraversalContext.visit **(/Users/zhanglei/Documents/workspace/meichuang/mc-main-app/node_modules/@umijs/bundler-utils/compiled/babel/index.js:89048:19)`**

**Comment by ErnestWangZuNian** [comment]
这个问题现在有啥进展嘛

**Comment by ErnestWangZuNian** [comment]
目前umi4 官方已经解决这个问题

**Comment by ErnestWangZuNian** [comment]
您好，我已收到邮件，我会尽快处理的。。。
