### ISSUE TITLE
子应用路由跳转 Error in nextTick: "NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node."

### ISSUE THREAD

**Issue by panshuang1** [jd-opensource/micro-app#556]
## 问题描述
> 问题的具体描述
子应用第一层跳转和第二层跳转都没有问题，第三层跳转就报错了 报错内容如下
VM671 vue.runtime.esm.js:4610 [Vue warn]: Error in nextTick: "NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node."
DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at invokeRawMethod (webpack-internal:///./node_modules/@micro-zoe/micro-app/lib/index.esm.js:1194:20)
    at invokePrototypeMethod (webpack-internal:///./node_modules/@micro-zoe/micro-app/lib/index.esm.js:1186:10)
    at commonElementHandler (webpack-internal:///./node_modules/@micro-zoe/micro-app/lib/index.esm.js:1235:14)
    at HTMLElement.insertBefore (webpack-internal:///./node_modules/@micro-zoe/micro-app/lib/index.esm.js:1274:12)
    at Object.insertBefore (webpack-internal:///./node_modules/_vue@2.7.10@vue/dist/vue.runtime.esm.js:6295:16)
    at insert (webpack-internal:///./node_modules/_vue@2.7.10@vue/dist/vue.runtime.esm.js:6614:29)
    at createComponent (webpack-internal:///./node_modules/_vue@2.7.10@vue/dist/vue.runtime.esm.js:6563:17)
    at createElm (webpack-internal:///./node_modules/_vue@2.7.10@vue/dist/vue.runtime.esm.js:6509:13)
    at updateChildren (webpack-internal:///./node_modules/_vue@2.7.10@vue/dist/vue.runtime.esm.js:6804:21)
    at patchVnode (webpack-internal:///./node_modules/_vue@2.7.10@vue/dist/vue.runtime.esm.js:6897:21)
## 复现步骤
1.
2.

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
![image](https://user-images.githubusercontent.com/23734192/186569947-981b2f28-0857-4e5a-8120-c4faefb760ef.png)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本："^0.8.10",
- 主应用前端框架&版本："vue": "^2.6.14","vue-router": "^3.5.1",
- 子应用前端框架&版本："vue": "^2.6.11","vue-router": "^3.2.0",
- 构建工具&版本：

**Comment by panshuang1** [comment]
> 
代码已经上传 
https://github.com/panshuang1/micro-app-demo01.git

**Comment by Huansheng1** [comment]
我也遇见了这个问题，有解决方案么，在使用ng的material 组件库的拖拽功能时会遇见该问题

**Comment by panshuang1** [comment]
暂时没有解决方案

**Comment by justrustc** [comment]
mark

**Comment by BrignLau** [comment]
这个问题好像没有解决，三级路由跳转还是会报错啊

**Comment by BrignLau** [comment]
@bailicangdu

**Comment by BrignLau** [comment]
我这边是 vite 子应用 vuerouter4
