### ISSUE TITLE
无法读取子应用window上的属性，Cannot read properties of undefined

### ISSUE THREAD

**Issue by Niefee** [jd-opensource/micro-app#639]
## 问题描述
> 问题的具体描述

引入子应用，报`TypeError: Cannot read properties of undefined (reading 'component')`，按照文档[子应用抛出错误信息：xxx 未定义](https://micro-zoe.github.io/micro-app/docs.html#/zh-cn/sandbox?id=_2%e3%80%81%e5%ad%90%e5%ba%94%e7%94%a8%e6%8a%9b%e5%87%ba%e9%94%99%e8%af%af%e4%bf%a1%e6%81%af%ef%bc%9axxx-%e6%9c%aa%e5%ae%9a%e4%b9%89) 试过几次不同方式，都不太行。

在子应用`main.js`添加
`window.Vue = Vue`也不行。

## 复现步骤
控制台报错：
```js
[micro-app from runScript] app sub-app-opm:  TypeError: Cannot read properties of undefined (reading 'component')
    at Module.fb15 (vuedraggable.umd.js:2449:1)
    at __webpack_require__ (vuedraggable.umd.js:32:1)
    at eval (vuedraggable.umd.js:96:1)
    at eval (vuedraggable.umd.js:99:1)
    at webpackUniversalModuleDefinition (vuedraggable.umd.js:10:1)
    at ./node_modules/vuedraggable/dist/vuedraggable.umd.js (vuedraggable.umd.js:12:1)
    at __webpack_require__ (bootstrap:726:1)
    at fn (bootstrap:103:1)
    at ./node_modules/babel-loader/lib/index.js?cacheDirectory!./node_modules/vue-loader/lib/index.js?!./node_modules/@xxx/timpc-components/src/lib/components/FormDesinger/MakingForm/MakingForm.vue?vue&type=script&lang=js& (MakingForm.vue?2111:21:1)
    at __webpack_require__ (bootstrap:726:1) http://localhost:9527/app.js
```
修改报错文件：
```js
// node_modules\vuedraggable\dist\vuedraggable.umd.js
if (typeof window !== "undefined" && "Vue" in window) {
  console.log('window:', window.Vue); // undefined
  console.log('"Vue" in window:', "Vue" in window); // true
  window.Vue.component("draggable", draggableComponent);
}
```

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本："@micro-zoe/micro-app": "1.0.0-alpha.10",
- 主应用前端框架&版本：
  - "vite": "^2.9.2",
    "vite-plugin-compression": "^0.5.1",
    "vite-plugin-eslint": "^1.6.0",
    "vite-plugin-vue-setup-extend": "^0.4.0",
    "vue-tsc": "^1.0.9"
    "vue": "^3.2.41",
    "vue-i18n": "^9.2.2",
    "vue-router": "^4.1.6"
- 子应用前端框架&版本：
  -   "vue": "2.5.17",
  -    "webpack": "4.16.5",
    "webpack-bundle-analyzer": "^3.3.2",
    "webpack-cli": "3.1.0",
    "webpack-dev-server": "^3.3.1",
    "webpack-merge": "4.1.4"
- 构建工具&版本：

**Comment by zzc1745** [comment]
我也遇到了这种问题，请问解决了吗
