### ISSUE TITLE
版本1.0.0-alpha.9、1.0.0-alpha.10下，子应用使用vuedraggable报错

### ISSUE THREAD

**Issue by dongdiya** [jd-opensource/micro-app#686]
## 问题描述
> 问题的具体描述
bug同
#639 

## 复现步骤
1.vue2子应用使用vuedraggable组件
2.vue2父应用安装micro-app 1.0.0-alpha.9及以上版本，子应用无法加载，报如下错误
```
index.esm.js?94a1:2396 [micro-app from runScript] app appname-vue2:  TypeError: Cannot read properties of undefined (reading 'component')
    at Module.fb15 (vuedraggable.umd.js?b76a:2445:1)
    at __webpack_require__ (vuedraggable.umd.js?b76a:30:1)
    at eval (vuedraggable.umd.js?b76a:94:1)
    at eval (vuedraggable.umd.js?b76a:97:1)
    at webpackUniversalModuleDefinition (vuedraggable.umd.js?b76a:3:1)
    at Object.eval (vuedraggable.umd.js?b76a:10:1)
    at ./node_modules/vuedraggable/dist/vuedraggable.umd.js (chunk-vendors.js:1572:1)
    at __webpack_require__ (app.js:856:30)
    at fn (app.js:153:20)
    at Object.eval (cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/pages/home.vue?vue&type=script&lang=js&:4:70) http://localhost:4008/child/vue2/js/app.js
```
**alpha.8及以下则没有问题**

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
![image](https://user-images.githubusercontent.com/39074676/205272319-67cf741c-f9b0-4d7b-a5f6-3b30c127cac4.png)

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。
[https://github.com/dongdiya/micro-app-demo.git](url)
## 环境信息
- micro-app版本：1.0.0-alpha.9、1.0.0-alpha.10
- 主应用前端框架&版本："vue": "^2.6.11"
- 子应用前端框架&版本："vue": "^2.6.11"
- 构建工具&版本：yarn  v1.22.19

**Comment by kelvin-lemon** [comment]
## Vuedraggable 库存在的问题
  vuedraggable 内判断 window 上是否有 Vue 通过 ：
  ```
  typeof window !== "undefined" && "Vue" in window
  ```
  详情见：https://github.com/SortableJS/Vue.Draggable/blob/431db153bfdfe09e31f622f01e9b3220b77e6b56/src/vuedraggable.js#L481
  这里只判断了 window 上是否有 Vue，而未判断 Vue 是否是 undefined 。

## MicroApp 库存在的问题：
MicroApp 内初始化 JS 沙盒的时候，强制隔离变量导致 Vue 被赋值到 代理 window 上且为 undefined，导致上面的报错。
详情见：https://github.dev/micro-zoe/micro-app/blob/a62a9fec645a7f58316aff2bdccdb2f3765e27df/src/sandbox/adapter.ts#L25-L26

## 解决方案：
1. @bailicangdu MicroApp 是否能删除默认 staticScopeProperties 内强制隔离的 Vue 变量。
2. vuedraggable 框架提 issue 更准确的判断 Vue 是否可用，加 && window.Vue。

**Comment by kelvin-lemon** [comment]
@bailicangdu 可能要帮忙看下为什么框架内需要默认处理 Vue 强制隔离，是否是为了解决 Vue3 CDN 引入时 var Vue = xxx 的问题？

**Comment by kelvin-lemon** [comment]
建议让业务侧配置是否隔离 Vue 吧，我之前用 0.8.10 版本套了 7、8 个 Vue2、Vue3 的子应用都是正常的，升级到 1.0.0-alpha.10 版本后 很多 Vue2 子应用都爆类似的问题

**Comment by bailicangdu** [comment]
确实是有上述问题，定义Vue为undefined是为了解决with沙箱的变量逃逸问题，比如 if(Vue){}会逃逸到外层原生window上查找。我们会尝试修复这个问题，感谢反馈

**Comment by wangjunpeng1015** [comment]
这个问题什么时候解决呢？在1.0.0-beta2中还未修复

**Comment by Luolei1992** [comment]
这个问题有解决吗

**Comment by lhz333** [comment]
这个问题还没有解决

**Comment by lh9403** [comment]
有解决方案么，想从乾坤换过来第一步就卡住了
