### ISSUE TITLE
[micro-app from runScript] app hosp:  TypeError: Cannot read properties of undefined (reading 'call')

### ISSUE THREAD

**Issue by chenzl0723** [jd-opensource/micro-app#740]
index.esm.js?1d4e:1759 [micro-app from runScript] app hosp:  TypeError: Cannot read properties of undefined (reading 'call')
    at __webpack_require__ (eval at runCode2Function (index.esm.js:1:1), <anonymous>:5031:33)
    at eval (eval at runCode2Function (index.esm.js:1:1), <anonymous>:6252:83)
    at __webpack_require__.O (eval at runCode2Function (index.esm.js:1:1), <anonymous>:5080:23)
    at eval (eval at runCode2Function (index.esm.js:1:1), <anonymous>:6255:53)
    at Proxy.eval (eval at runCode2Function (index.esm.js:1:1), <anonymous>:6257:12)
    at eval (eval at runCode2Function (index.esm.js:1:1), <anonymous>:6259:4)
    at eval (eval at runCode2Function (index.esm.js:1:1), <anonymous>:6259:337)
    at runCode2Function (index.esm.js?1d4e:1845:1)
    at runScript (index.esm.js?1d4e:1753:1)
    at eval (index.esm.js?1d4e:1720:1)

**Comment by hi-asan** [comment]
参考：https://github.com/vueComponent/ant-design-vue-pro

根据 ant-design-pro项目，作为基座应用与子应用Demo。修改`src/permission.js`路由守卫，让所有的请求都`next()`

在`App.vue`中，加入以下代码
```
...
<micro-app style="width: 100%;height: 800px" name='app1' url=' http://192.168.110.9:8001/'></micro-app>

...
import microApp from '@micro-zoe/micro-app'
created(){
   microApp.start()
}
```

可重现上面的问题，其中子应用也是一个ant-design-vue-pro工程
