### ISSUE TITLE
基座下跳转不同的嵌套了子应用的页面，在返回上一页时会地址栏展示不正确，导致渲染错误

### ISSUE THREAD

**Issue by hengwuming** [jd-opensource/micro-app#941]
## 问题描述
> 问题的具体描述
基座下跳转不同的嵌套了子应用的页面，在返回上一页时会地址栏展示不正确，导致渲染错误
## 复现步骤
1.基座下存在a,b两个页面，b页面存在一个按钮，点击事件为this.$router.back()，均嵌套了子应用
2.在a页面跳转到b页面时，在页面内容加载时，一直点击b页面的按钮，能回退到a页面，但是地址栏会在进入一瞬间展示正确的地址，然后变成b页面的地址，此时需要将子应用延迟加载，否则会正常渲染。在a页面打印this.$route.path为a的地址，但是地址显示为b的地址。
3.在所有生命周期钩子打印，均正常执行，error钩子未执行
## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
- micro-app版本：0.8.11
- 主应用前端框架&版本：vue 2.6.11
- 子应用前端框架&版本：vue 2.6.11
- 构建工具&版本：webpack 4.46.0

**Comment by bailicangdu** [comment]
理论上存在这种可能，能提供个复现的demo吗

**Comment by hengwuming** [comment]
> 理论上存在这种可能，能提供个复现的demo吗

好的，晚上下班了，我尝试写个demo能不能复现

**Comment by hengwuming** [comment]
> 理论上存在这种可能，能提供个复现的demo吗
抱歉，我在我的demo中不能复现， 但是我写了一下公司代码中的逻辑，大概就是a页面跳转到b页面，跳转时携带一个id，b页面通过id去请求接口获取配置然后渲染对应的子应用，这是demo地址：https://github.com/hengwuming/micdemo

**Comment by hengwuming** [comment]
> 理论上存在这种可能，能提供个复现的demo吗

有个报错忘记贴了，抱歉抱歉

index.js:1 [micro-app] app sub-xxxx-xxxxx: an error occurred in the unmount function 
 TypeError: q is not a function
    at e.unmount (eval at runCode2Function (index.esm.js:1:1), <anonymous>:23:33226)
    at CreateApp.y [as umdHookUnmount] (eval at runCode2Function (index.esm.js:1:1), <anonymous>:3:3840)
    at CreateApp.unmount (index.esm.js:3072:1)
    at MicroAppElement.handleUnmount (index.esm.js:3459:1)
    at MicroAppElement.disconnectedCallback (index.esm.js:3271:1)
    at HTMLDivElement.removeChild (index.esm.js:1167:1)
    at Object.removeChild (vue.min.js:6:41102)
    at l (vue.min.js:6:56312)
    at n (vue.min.js:6:58423)
    at w (vue.min.js:6:58602)

**Comment by bailicangdu** [comment]
目前子应用一旦渲染是不可暂停的，但确实存在渲染到一半被卸载的情况，对于这个问题我们会进行修复
