### ISSUE TITLE
升级 v1.0 使用 echarts 默认下载图片报错

### ISSUE THREAD

**Issue by huoshanxue** [jd-opensource/micro-app#951]
## 问题描述
> 由 0.8.5  升级 v1.0 ，子系统使用 echarts 下载图片报错
```
Uncaught TypeError: Failed to construct 'MouseEvent': Failed to read the 'view' property from 'UIEventInit': Failed to convert value to 'Window'.
    at SaveAsImage.onclick (SaveAsImage.js:80:1)
    at Eventful.trigger (Eventful.js:103:1)
    at Handler.dispatchToElement (Handler.js:141:1)
    at Handler.<computed> [as click] (Handler.js:248:1)
    at Eventful.trigger (Eventful.js:103:1)
    at localDOMHandlers.<computed> (HandlerProxy.js:162:1)
    at HTMLDivElement.eval (HandlerProxy.js:209:1)
```
## 复现步骤
1. 用的是官方默认的demo，可以在仓库里面复现，启动 vue2 主和子项目，子系统 首页就有添加了图表，点击下载即可复现

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

![image](https://github.com/micro-zoe/micro-app/assets/52485428/652746f5-cf15-473d-b1e1-fe637b79b801)
![image](https://github.com/micro-zoe/micro-app/assets/52485428/fb40b7d4-aaf5-4bfb-9fc9-0365cdb75dbe)

## 复现仓库
> [请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。](https://github.com/huoshanxue/micro-app-issue-demo)

## 环境信息
- micro-app版本： ^1.0.0-rc.2
- 主应用前端框架&版本：vue2
- 子应用前端框架&版本：vue2 + echarts^5.4.3
- 构建工具&版本：vue-cli  4

**Comment by adntian** [comment]
echarts的源码中，是有处理的，但实际使用的时候，还是会报一个Failed to convert value to 'Window'.的错误，使用rawWindow就没有问题
```
var evt = new MouseEvent('click', {
            // some micro front-end framework， window maybe is a Proxy
            view: document.defaultView,
            bubbles: true,
            cancelable: false
          });
```

**Comment by huoshanxue** [comment]
https://github.com/huoshanxue/micro-app-issue-demo
可以复现有没有大佬看一下这个问题呢

**Comment by huoshanxue** [comment]
![Snipaste_2024-01-15_10-38-22](https://github.com/micro-zoe/micro-app/assets/52485428/2439786d-fe16-4e94-a1b3-77abe5877ffc)
目前只能修改源码了，官方会看一下这个问题吗
@bailicangdu

**Comment by huoshanxue** [comment]
使用iframe可解决
