### ISSUE TITLE
使用next.js v14作为子应用接入时不能正常显示

### ISSUE THREAD

**Issue by Bournegithub** [jd-opensource/micro-app#970]
## 问题描述
> 问题的具体描述
接入next.js ssr子应用，未能如预期显示子应用的页面

例如接入的是/next14/single页面，但是在主应用只能显示/next14页面,无报错.
此时点击基座其他路由，会全屏幕展示子应用的/next页面，主应用的其他部分都丢失，路由也不会跳转，并报错

Uncaught Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at t2 (fd9d1056-5517b4ab1905cb09.js:3:24426)
    at iU (fd9d1056-5517b4ab1905cb09.js:3:120022)
    at o2 (fd9d1056-5517b4ab1905cb09.js:3:94766)
    at eval (fd9d1056-5517b4ab1905cb09.js:3:94588)
    at o1 (fd9d1056-5517b4ab1905cb09.js:3:94595)
    at n1 (fd9d1056-5517b4ab1905cb09.js:3:37678)
    at eval (fd9d1056-5517b4ab1905cb09.js:3:130740)
    at uS (fd9d1056-5517b4ab1905cb09.js:3:130822)
    at uk (fd9d1056-5517b4ab1905cb09.js:3:129771)
t2 @ fd9d1056-5517b4ab1905cb09.js:3
iU @ fd9d1056-5517b4ab1905cb09.js:3
o2 @ fd9d1056-5517b4ab1905cb09.js:3
eval @ fd9d1056-5517b4ab1905cb09.js:3
o1 @ fd9d1056-5517b4ab1905cb09.js:3
n1 @ fd9d1056-5517b4ab1905cb09.js:3
eval @ fd9d1056-5517b4ab1905cb09.js:3
uS @ fd9d1056-5517b4ab1905cb09.js:3
uk @ fd9d1056-5517b4ab1905cb09.js:3

## 复现步骤
1. 拉取代码，npm i, npm run dev

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。
<img width="1423" alt="截屏2023-11-18 下午2 58 06" src="https://github.com/micro-zoe/micro-app/assets/17694691/fd75a476-319e-4500-a9a7-a6908698d84e">

<img width="1421" alt="截屏2023-11-18 下午2 57 37" src="https://github.com/micro-zoe/micro-app/assets/17694691/3d2d1785-061b-4ccd-ab93-7d0841004fcf">

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

https://github.com/Bournegithub/demoForMicroAppMain

## 环境信息
- micro-app版本：
- 主应用前端框架&版本：vue 3.3.4
- 子应用前端框架&版本：next 14.0.2
- 构建工具&版本：vite 4.4.11

**Comment by GUOYUHAN** [comment]
解决了吗

**Comment by n1203** [comment]
我遇到了和你一样的问题

**Comment by cosaaa** [comment]
解决了吗

**Comment by cosaaa** [comment]
子应用不要使用turbopack打包
